[package]
name = "julia"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.26"
env_logger = "0.9"
log = "0.4"
wgpu = "0.13"
image = "0.24"
pollster = "0.2"
game-loop = { version = "*", features = [ "window" ] }
bytemuck = { version = "*", features = [ "derive" ] }